version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=simplebank
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1033
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d simplebank"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:1033@postgres:5432/simplebank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
